// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户信息表
type User struct {
	ID          int32      `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Username    string     `gorm:"column:username;type:varchar(20);not null" json:"username"`
	Password    string     `gorm:"column:password;type:varchar(64);not null" json:"password"`
	IsDelete    bool       `gorm:"column:is_delete;type:tinyint(1);not null;comment:1表示用户已经被删除，0表示可用" json:"is_delete"`                       // 1表示用户已经被删除，0表示可用
	Description *string    `gorm:"column:description;type:text;comment:备注信息" json:"description"`                                              // 备注信息
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6);comment:记录创建时间" json:"created_at"` // 记录创建时间
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6);comment:记录更新时间" json:"updated_at"` // 记录更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
